### ISSUE TITLE
"require 'forwardable'" missing from soapforce-0.5.0 gem on rubygems.org

### ISSUE THREAD

**Issue by mikeburr** [TinderBox/soapforce#15]
Looks like the soapforce gem on rubygems.org did not pick up the most recent commit to add forwardable to soapforce.rb?

$ gem environment remotesources
https://rubygems.org/

$ gem list soapforce

**\* LOCAL GEMS ***

soapforce (0.5.0)

$ cat $(gem environment gemdir)/gems/soapforce-0.5.0/lib/soapforce.rb
require 'savon'

require "soapforce/version"
require "soapforce/configuration"

require "soapforce/client"
require "soapforce/result"
require "soapforce/query_result"
require "soapforce/sobject"

module Soapforce

end

**Comment by jheth** [comment]
New gem version 0.6.0 pushed tonight resolves this issue.
