### ISSUE TITLE
Modify Timeout Options?

### ISSUE THREAD

**Issue by Nerdenberger** [TinderBox/soapforce#17]
Hello,
Is it possible to modify the open_timeout and read_timeout options in the Savon client that Soapforce creates?  I have some batch upsert operations that can take anywhere from 20-100 seconds to complete which seems to be above the 60 second default.

Thanks!

Nick

**Comment by jheth** [comment]
Hey @Nerdenberger, that's a good idea to open up more Savon options. I'd be happy to add those or I'll accept a patch if you have one.

**Comment by jheth** [comment]
@Nerdenberger See #19 for the resolution.
