### ISSUE TITLE
Misleading info in readme for `destroy` call

### ISSUE THREAD

**Issue by hamzatayeb** [TinderBox/soapforce#9]
I’ve recently run into an issue where I get -

`ArgumentError: wrong number of arguments (2 for 1)`

when attempting to call the `destroy` method in the manner described on the readme.

The [section in question](https://github.com/TinderBox/soapforce#destroy) clearly shows the sObject name being passed as the first argument, followed by a Salesforce ID (or an array of IDs as the case may be).

This no longer appears to work. Instead simply omitting the sObject name and passing the ID itself does the job (which makes sense anyway since the ID namespace is global across all sObjects in Salesforce, so there is no real need for the sObject name in this call anyways).

Please update the doc accordingly.

**Comment by jheth** [comment]
Thanks.  I've fixed this here: 
https://github.com/TinderBox/soapforce/commit/b039744286482564dab4db1ada30b959b938dea6

I tagged to the wrong issue.
